# Generated by Django 5.2.6 on 2025-09-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='recognized_text',
            field=models.TextField(blank=True, null=True, verbose_name='Распознанный текст'),
        ),
    ]
